server:
  port: 8081
spring:
  data:
    neo4j:
      uri: bolt://123.249.11.83:7687
      username: neo4j
      password: 12345
#    mongodb:
#      host: 123.249.11.83
#      port: 27017
#  redis:
#    host: 123.249.11.83
#    port: 8080


